logo: /assets/headshot_circle.jpg
title: Martin Múdry
description: Data Analysis, Business Intelligence, Supply Chain Optimization
linkedin_username: martin-mudry-aa619b15a
social_links:
- { platform: linkedin,       user_url: "https://www.linkedin.com/in/martin-mudry-aa619b15a/" }
show_downloads: false
theme: minima
